# Generated by Django 4.2.4 on 2023-08-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTLV', '0002_alter_relacionpedidosproductos_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionpedidosproductos',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTLV.productos'),
        ),
    ]
